name: Create Archive
on: 
  release:
    branches: [ "main" ]
    types: ["published"]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    - name: Zip Folder
      run: zip -r "FS22_HarvestFillMonitor.zip" . -x ".git/*" ".github/*" ".gitignore"

   
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "FS22_HarvestFillMonitor.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
